# https://aka.ms/yaml

trigger:
  batch: false
  branches:
    include: 
    - master

pr: [ master ]

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

strategy:
  matrix:
    windows-stable:
      imageName: 'vs2017-win2016'
      rustup_toolchain: stable
    windows-nightly:
      imageName: 'vs2017-win2016'
      rustup_toolchain: nightly
    mac-nightly:
      imageName: 'macos-10.13'
      rustup_toolchain: nightly
    mac-stable:
      imageName: 'macos-10.13'
      rustup_toolchain: stable
    linux-stable:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: stable
    linux-nightly:
      imageName: 'ubuntu-16.04'
      rustup_toolchain: nightly

pool:
  vmImage: $(imagename)

steps:
  - checkout: self
    submodules:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    displayName: Windows install rust
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      echo ##vso[task.setvariable variable=PLATFORM;]win64
      echo ##vso[task.setvariable variable=WIRESHARK_BASE_DIR;]C:/wireshark-libs
    displayName: Windows set environment variables
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: cargo build --all --verbose
    displayName: Cargo build
  - script: cargo test --all --verbose
    displayName: Cargo test